[package]
name = "esp-idf-sys"
version = "0.28.2"
authors = ["Alexey Arbuzov <aarbuzov@termt.com>", "sapir <yasapir@gmail.com>", "Ivan Markov <ivan.markov@gmail.com>"]
edition = "2018"
resolver = "2"
categories = ["embedded", "hardware-support"]
keywords = ["sys", "idf", "esp-idf", "esp32"]
description = "Bindings for ESP-IDF (Espressif's IoT Development Framework)"
repository = "https://github.com/esp-rs/esp-idf-sys"
license = "MIT OR Apache-2.0"
readme = "README.md"
links = "esp_idf"
build = "build/build.rs"

[features]
default = ["std", "pio"]

std = ["embedded-svc/std"]
alloc_handler = []
panic_handler = []
binstart = []
libstart = []

# Use `platformio` to build the `esp-idf`
pio = ["embuild/pio"]
# Experimental: Use native `esp-idf` tooling to build it
native = ["embuild/cmake", "embuild/espidf"]

[dependencies]
mutex-trait = "0.2"
embedded-svc = { version = "0.15.4", default-features = false }
paste = "1"

[build-dependencies]
embuild = { version = "0.27", features = ["glob"] }
anyhow = "1"
strum = { version = "0.21", features = ["derive"] }
regex = "1.5"
bindgen = "0.59.2"
